using ProjectPFE.Models.EntityDataBase;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectPFE.Models
{
    public class Amende:EntityBase
    {
        public enum Statut { Amende_non_affecté, Site_affecte, Conducteur_affecte, Amende_accepte, Acceptation_envoye };
        // Entity Framework assumes that primary key values are generated by the database
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Key]
        public Guid AmendeId { get; set; }
        [Required]
        [MaxLength(40)]
        public string Num_Avis { get; set; }
        [Required]
        public DateTime Date_Avis { get; set; }
        [Required]
        public DateTime Date_Infraction { get; set; }
        [Required]
        public string Lieu_Infraction { get; set; }
        [Required]
        public float Montant { get; set; }

        [Column(TypeName = "NVARCHAR(MAX)")]
        public string Fiche_Amende { get; set; }
        public string Description { get; set; }
        public string Num_Agent { get; set; }
        public string CodeService_Agent { get; set; }
        public DateTime creation { get; set; }


        [ForeignKey("VehiculeId")]
        public Vehicule vehicule { get; set; }
        public Guid? VehiculeId { get; set; }

        [ForeignKey("Id")]
        public Employee Employee { get; set; }
        public string EmployeeId { get; set; }


        public Statut statut { get; set; }
        
        [ForeignKey("ConducteurId")]
        public conducteur conducteur { get; set; }
        public Guid? ConducteurId { get; set; }

        //? nullable
        [ForeignKey("siteId")]
        public Site site { get; set; }
        public Guid siteId { get; set; }

        public Amende()
        {
            AmendeId =  Guid.NewGuid();
            creation = DateTime.Now;
        }
    }
}
